collections:
  offerings:
    output: true
    permalink: /:slug

# Enable LiveReload
livereload: true

# Site settings
title: FAF9F6
description: 
url: "https://www.brittanywoodard.com"  
baseurl: ""  # leave empty if site is served at domain root
lang: en
timezone: America/New_York

author:
  name: FAF9F6
  url: "https://www.brittanywoodard.com"

logo: "/uploads/gentle-within-17.png"
social:
  name: FAF9F6
  links:
    - https://www.instagram.com/{{ site.site-settings.social.instagram_username }}
    - https://www.linkedin.com/{{ site.site-settings.social.linkedin_username }}

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

